version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.platform:org.eclipse.core.commands"
        versions: ">= 3.10.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.core.resources"
        versions: ">= 3.15.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.core.runtime"
        versions: ">= 3.22.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.core.variables"
        versions: ">= 3.5.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.debug.core"
        versions: ">= 3.17.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.common"
        versions: ">= 3.15.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.registry"
        versions: ">= 3.10.200"
      - dependency-name: "org.eclipse.platform:org.eclipse.text"
        versions: ">= 3.12.0"
      - dependency-name: "org.eclipse.jdt:org.eclipse.jdt.launching"
        versions: ">= 3.18.0"
  - package-ecosystem: "maven"
    directory: "/src/it/test"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/webapp"
    schedule:
      interval: "daily"
